#!/usr/bin/python

from upsilon import http, config

parser = config.commonArgumentParser()
args = parser.parse_args();

client = http.getHttpClient(args.ssl, args.server, args.port);
resp = http.getHttpContent(client, "/peerUpdate")

print resp
