#!/usr/bin/python

from upsilonCommon import http, config

parser = config.commonArgumentParser()
args = parser.parse_args();

client = http.getHttpClient(args.ssl, args.address, args.port);
resp = http.getHttpContent(client, "/peerUpdate")

print resp
