#!/usr/bin/python

from upsilon import amqp, config
import pika
import sys

def onMessage(channel, method, properties, body):
    print body, properties

    channel.basic_ack(delivery_tag = method.delivery_tag)
    sys.exit(0)

parser = config.commonArgumentParser()
parser.add_argument('itemType')
parser.add_argument('id', type = int)
args = parser.parse_args()

conn = amqp.Connection(args.server, callback = onMessage)
conn.bind("upsilon.custodian.results")

print("publishing")

newReq = args.itemType + "/" + str(args.id)

headers = {}
headers["upsilon-msg-type"] = "GET_ITEM"
headers["itemType"] = args.itemType;
headers["itemId"] = args.id

props = pika.BasicProperties(headers = headers)
conn.channel.basic_publish(exchange = "ex_upsilon", routing_key = 'upsilon.custodian.gets', properties = props)

conn.startConsuming()
