#!/usr/bin/python

import pika

QUEUE_NAME = 'upsilon-amqp-ping'
EXCHANGE_NAME = 'ex_upsilon'
ROUTING_KEY = 'upsilon'

connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))


callback_queue = "pingreps"

headers = dict()
headers['upsilon-msg-type'] = 'REQ_NODE_SUMMARY'
props = pika.BasicProperties(headers = headers, reply_to = QUEUE_NAME)

channel = connection.channel()
channel.queue_declare(queue = QUEUE_NAME, durable = False)
channel.queue_bind(queue = QUEUE_NAME, exchange = EXCHANGE_NAME, routing_key = ROUTING_KEY)

channel.basic_publish(exchange = EXCHANGE_NAME, routing_key = 'upsilon', body = '', properties = props)

def callback(ch, method, properties, body):
	print "recv ", body

	ch.basic_ack(delivery_tag = method.delivery_tag, multiple = False)

channel.basic_consume(callback, queue = QUEUE_NAME)
channel.start_consuming();

connection.close()
