- job:
    name: jjb-upsilon-node
    description: "Compiles upsilon-node and produces a release archive"
    project-type: freestyle

    logrotate: 
        numToKeep: 3

    scm: 
        - git: 
            skip-tag: false
            url: https://github.com/upsilonproject/upsilon-node.git
            triggers:
                - pollscm: '@hourly'

    wrappers:
        - ansicolor

- job:
    name: jjb-upsilon-node-rpm-fedora
    description: "Makes a release RPM"
